### ISSUE TITLE
Осуществление платежей

### ISSUE THREAD

**Issue by evgkord** [alfa-laboratory/alfalink-1c-directbank-via-api#7]
Платеж, в котором ООО "Тест Директ Банк" переводит деньги ООО "Тест Директ банк Получатель"  осуществляется нормально.

Можно ли как-то осуществить платеж, в котором ООО "Тест Директ банк Получатель" переводит деньги ООО "Тест Директ Банк"? (см.пример [document.txt](https://github.com/alfa-laboratory/alfalink-1c-directbank-via-api/files/7346787/document.txt). При отправке такого платежа, подписанного сертификатом directBank_cert_psw_123456.pfx, в ответе указано "У владельца сертификата нет полномочий на проведение операций по номеру счета 40702810300000019796.

Также интересно, можно ли получить выписку для счета  40702810300000019796 (ООО "Тест Директ банк Получатель") и убедится, что ему пришли деньги. В ответе на запрос выписки указано <Code>1013</Code><Description>Недостаточно прав на операции с расчетным счетом</Description>. Получается можно запрашивать выписку только по счету 40702810701300009144 (ООО "Тест Директ Банк") ?

**Comment by artik008** [comment]
Добрый день!
ООО "Тест Директ банк Получатель" - компания не подключена к Альфа-Линк 1С:Директбанк, она настроена как сторонняя компания получатель. Поэтому операции по ней недоступны.

Мы можем проверить внутри системы, что ваш тестовый платёж прошёл. Для этого можете написать письмо с указанием времени отправки платежа. Однако, платёж должен отображаться в выписке ООО "Тест Директ Банк", что означает, что он исполнен на стороне банка корректно.
